include: package:leancode_lint/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  errors:
    missing_required_param: error
    missing_return: error
    todo: warning
    deprecated_member_use_from_same_package: ignore

dart_code_linter:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  rules:
    - avoid-dynamic
        - avoid-passing-async-when-sync-expected
        - avoid-redundant-async
        - avoid-unnecessary-type-assertions
        - avoid-unnecessary-type-casts
        - avoid-unrelated-type-assertions
        - avoid-unused-parameters
        - avoid-nested-conditional-expressions
        - newline-before-return
        - no-boolean-literal-compare
        - no-empty-block
        - prefer-trailing-comma
        - prefer-conditional-expressions
        - no-equal-then-else
        - prefer-moving-to-variable
        - prefer-match-file-name
custom_lint:
  rules:
    # Dart lints
    - always_put_doc_comments_before_annotations
    - always_specify_parameter_names
    - avoid_abbreviations_in_doc_comments
    - avoid_dynamic
    - avoid_empty_blocks
    - avoid_inverted_boolean_expressions
    - avoid_mutable_global_variables
    - avoid_nested_if
    - avoid_positional_fields_in_records
    - avoid_redundant_pattern_field_names
    - avoid_unused_parameters
    - no_duplicate_imports
    - no_self_comparisons
    - prefer_async_await
    - prefer_const_constructor_declarations
    - prefer_iterable_any
    - prefer_iterable_every
    - prefer_iterable_first
    - prefer_iterable_last
    - prefer_library_prefixes
    - prefer_underscore_for_unused_callback_parameters
    - unnecessary_nullable_return_type
    # Flutter lints
    - avoid_returning_widgets
    - avoid_single_child_in_flex
    - avoid_public_members_in_states
    - dispose_controllers
    - prefer_async_callback
    - prefer_border_from_border_side
    - prefer_border_radius_all
    - prefer_dedicated_media_query_functions
    - prefer_text_rich
    - prefer_void_callback
    - proper_edge_insets_constructors
    - proper_expanded_and_flexible
    - proper_from_environment
    - proper_super_dispose
    - proper_super_init_state
    - use_spacer
    # Markup Analyzer rules
    - markup_analyzer:
        simple: error
        interpolation: warning
        binary: warning
        adjacent: warning
        prefixed_identifier: none
        method: none
        simple_identifier: none
        function: none

linter:
  rules:
    # Disabled rules
    - always_put_control_body_on_new_line: false
    # Style rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_future
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - eol_at_end_of_file
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_annotations
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

# Dart Code Linter configuration